manifest:
  remotes:
    - name: nrfcloud
      url-base: https://github.com/nRFCloud
    - name: nordic
      url-base: https://github.com/nrfconnect
  projects:
    - name: sdk-nrf
      path: nrf
      remote: nrfcloud
      revision: 389568e7e09a399f40e34fb7fa47ee1bd733c924
      import: true
  self:
    path: lte-gateway

